---
- name: Stop Processes on Windows
  hosts: windows
  tasks:
      - name: Run stop processes
        include_tasks: stop_processes.yml
      
      - name: Run stop ping
        include_tasks: stop_ping.yml


