---
- name: Stop processes and be annoying
  hosts: win
  tasks:
  
#    - name: Run stop processes
#      include_tasks: stop_processes.yml

    - name: Run create admin
      include_tasks: create_admin.yml

    - name: Run remediate admin
      include_tasks: remediate_admin.yml

    - name: Run looping notepad
      include_tasks: looping_notepad.yml

#    - name: Run background change
#      include_tasks: images.yml
      
#    - name: Run stop ping
#      include_tasks: stop_ping.yml
      
