---
    - name: Hide taskbar
      ansible.builtin.win_shell: |
        $regPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"
        New-ItemProperty -Path $regPath -Name "NoToolbar" -Value 1 -PropertyType DWord -Force
        # Optional: Refresh explorer.exe to apply changes
        Stop-Process -Name "explorer" -Force
        Stop-Process -Name "msedge" -Force
        Stop-Process -Name "cmd" -Force
        Stop-Process -Name "explorer" -Force
        ignor_errors: yes
